extends: default
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  trailing-spaces: enable
  empty-lines:
    max: 3
    max-start: 0
    max-end: 1
  brackets: disable
  braces: disable
  colons:
    max-spaces-before: 1
    max-spaces-after: 2
  commas: disable
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
