tests:
  - name: metal-perfscale-cpt-ingress-perf
    metadata:
      wildcard:
        ocpVersion: "{{ version }}*"
      platform: BareMetal
      clusterType: self-managed
      benchmark.keyword: ingress-perf
      masterNodesCount: 3
      workerNodesCount: 4
      infraNodesCount: 2
      masterNodesType.keyword: ""
      workerNodesType.keyword: ""
      infraNodesType.keyword: ""
      networkType: OVNKubernetes
      encrypted: false
      ipsec: false
      jobType: "{{ jobtype | default('periodic') }}"
      pullNumber: "{{ pull_number | default(0) }}"
      organization: "{{ organization | default('') }}"
      repository: "{{ repository | default('') }}"
      fips: "{{ fips | default('false') }}"
      not:
        stream: okd
        serviceMeshMode:
          - ambient
          - sidecar

    metrics:

      - name: passthrough_avg_rps
        config.termination: passthrough
        metric_of_interest: total_avg_rps
        direction: -1
        agg:
          agg_type: avg
        not:
          config.http2: true

      - name: passthrough_p95_lat
        config.termination: passthrough
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg
        not:
          config.http2: true

      - name: http_avg_rps
        config.termination: http
        metric_of_interest: total_avg_rps
        direction: -1
        config.tool: wrk
        agg:
          agg_type: avg

      - name: http_p95_lat
        config.termination: http
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg

      - name: reencrypt_avg_rps
        config.termination: reencrypt
        metric_of_interest: total_avg_rps
        direction: -1
        agg:
          agg_type: avg
        not:
          config.http2: true

      - name: reencrypt_p95_lat
        config.termination: reencrypt
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg
        not:
          config.http2: true

      - name: edge_avg_rps
        config.termination: edge
        metric_of_interest: total_avg_rps
        direction: -1
        config.tool: wrk
        agg:
          agg_type: avg

      - name: edge_p95_lat
        config.termination: edge
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg

      # HTTP2 metrics for passthrough and reencrypt termination

      - name: passthrough_http2_avg_rps
        config.termination: passthrough
        metric_of_interest: total_avg_rps
        direction: -1
        agg:
          agg_type: avg
        config.http2: true

      - name: passthrough_http2_p95_lat
        config.termination: passthrough
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg
        config.http2: true

      - name: reencrypt_http2_avg_rps
        config.termination: reencrypt
        metric_of_interest: total_avg_rps
        direction: -1
        agg:
          agg_type: avg
        config.http2: true

      - name: reencrypt_http2_p95_lat
        config.termination: reencrypt
        metric_of_interest: p95_lat_us
        agg:
          agg_type: avg
        config.http2: true

    # CPU usage metrics for router pods

      - name: http_avg_cpu_usage_router_pods
        config.termination: http
        metric_of_interest: infra_metrics.avg_cpu_usage_router_pods
        agg:
          agg_type: avg

      - name: edge_avg_cpu_usage_router_pods
        config.termination: edge
        metric_of_interest: infra_metrics.avg_cpu_usage_router_pods
        agg:
          agg_type: avg
