name: CI tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    uses: ./.github/workflows/pylint.yaml

  build:
    needs: lint
    uses: ./.github/workflows/builders.yaml

  unit_tests:
    needs: lint
    uses: ./.github/workflows/unit_tests.yaml

  integration_tests:
    needs: [lint, unit_tests]
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
